name:                ccs

dependencies:
- base >= 4.7 && < 5
- containers
- parsec
- tasty
- tasty-hunit

library:
  source-dirs:          lib
  exposed-modules:
    - CCSAst
    - CCSParser
    - CCSValidate
    - CCSMosml

executable:
    main:                Main.hs
    source-dirs:         src

tests:
  blackbox-test:
    main:                Test.hs
    source-dirs:         test
    dependencies:
    - ccs
