name:                ccs

dependencies:
- base >= 4.7 && < 5
- containers
- parsec
- tasty
- tasty-hunit
- transformers
- mtl
- directory

library:
  source-dirs:          lib
  exposed-modules:
    - CCSAst
    - CCSParser
    - CCSValidate
    - CCSMosml
    - CCSTypecheck

executable:
    main:                Main.hs
    source-dirs:         src
    dependencies:
    - ccs 

tests:
  blackbox-test:
    main:                Test.hs
    source-dirs:         test
    dependencies:
    - ccs
